# Generated by Django 4.2.7 on 2025-10-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=40)),
                ("curso", models.CharField(blank=True, max_length=200)),
                ("semestre", models.PositiveIntegerField(default=1)),
                ("habilidades", models.TextField(blank=True)),
                ("senha", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=40)),
                ("area_atuacao", models.CharField(blank=True, max_length=200)),
                ("cnpj", models.CharField(blank=True, max_length=20)),
                ("senha", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("requisitos", models.TextField(blank=True)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vagas",
                        to="core.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aceita", "Aceita"),
                            ("rejeitada", "Rejeitada"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidaturas",
                        to="core.aluno",
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidaturas",
                        to="core.vaga",
                    ),
                ),
            ],
            options={
                "unique_together": {("aluno", "vaga")},
            },
        ),
    ]
